{% set python_min = '3.10' %}
{% set name = "openpathsampling-cli" %}
{% set version = "0.3.1" %}
{% set sha256 = "8a96c6675ab8d1c2eeb7293e346c2e3b0040f752aefb7b2449f1e0978baa71bd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  entry_points:
    - openpathsampling = paths_cli.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - click
    - tqdm
    - openpathsampling >=1.6

test:
  requires:
    - python {{ python_min }}
  imports:
    - paths_cli
    - paths_cli.tests

about:
  home: https://github.com/openpathsampling/openpathsampling-cli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line tools for OpenPathSampling

  description: |
    OpenPathSampling (OPS) is a powerful Python library for path sampling
    simulations. The openpathsampling-cli package provides a useful
    command line interface for working with OPS files and for running OPS
    simulations. 
  doc_url: https://openpathsampling-cli.readthedocs.io/
  dev_url: https://github.com/openpathsampling/openpathsampling-cli

extra:
  recipe-maintainers:
    - dwhswenson
