{% set name = "openpathsampling-cli" %}
{% set version = "0.1.1" %}
{% set sha256 = "5fb7123ff9db80141d9f8ab7f6fb0f6a6d3911746f5bd60ba2d8589d4743cf87" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - openpathsampling = paths_cli.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - tqdm
    - openpathsampling >=1.2

test:
  imports:
    - paths_cli
    - paths_cli.tests

about:
  home: https://github.com/openpathsampling/openpathsampling-cli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line tools for OpenPathSampling

  description: |
    OpenPathSampling (OPS) is a powerful Python library for path sampling
    simulations. The openpathsampling-cli package provides a useful
    command line interface for working with OPS files and for running OPS
    simulations. 
  doc_url: https://openpathsampling-cli.readthedocs.io/
  dev_url: https://github.com/openpathsampling/openpathsampling-cli

extra:
  recipe-maintainers:
    - dwhswenson
